import "./globals.css";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Inter } from "next/font/google";
import { Header } from "../components/layout/Header";
import { Footer } from "../components/layout/Footer";
import { AnnouncementBar } from '../components/layout/AnnouncementBar'; 

import SmoothScroll from "../components/layout/SmoothScroll";
import PageTransition from "../components/layout/PageTransition";

const inter = Inter({ subsets: ["latin"] });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "School ERP - The Ultimate Management Solution",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const _htmlProps = { suppressHydrationWarning: true } as any;

  return (
    /* suppressHydrationWarning: guard against harmless hydration mismatches caused by dev extensions
       or injected attributes (e.g. webcrx) that can appear in the DOM before React hydrates. */
    <html lang="en" {..._htmlProps}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${inter.className} antialiased`}
      >
          <PageTransition>
            <AnnouncementBar /> 
            <Header />
            <SmoothScroll>{children}</SmoothScroll>
            <Footer />
          </PageTransition>
      </body>
    </html>
  );
}
