import "./globals.css";
import type { Metadata } from "next";
import { Inter, Manrope, Work_Sans } from "next/font/google";
import { Header } from "../components/layout/Header";
import { Footer } from "../components/layout/Footer";
import { AnnouncementBar } from '../components/layout/AnnouncementBar'; 

import SmoothScroll from "../components/layout/SmoothScroll";
import PageTransition from "../components/layout/PageTransition";

const inter = Inter({ subsets: ["latin"] });

const manrope = Manrope({
  subsets: ["latin"],
  variable: "--font-manrope",
  weight: ["400", "700"],
});

const worksans = Work_Sans({
  subsets: ["latin"],
  variable: "--font-worksans",
  weight: ["300", "400", "700", "800"],
});

// Note: Geist font imports removed because they are not available via Google Fonts.
// If you need a similar UI font, use `Inter` or add a supported Google font here.

export const metadata: Metadata = {
  title: "School ERP - The Ultimate Management Solution",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${manrope.variable} ${worksans.variable} ${inter.className} antialiased`}
      >
          <AnnouncementBar /> 
          <Header />
          <SmoothScroll><PageTransition>{children}</PageTransition></SmoothScroll>
          <Footer />
      </body>
    </html>
  );
}
